#!/usr/bin/env python3
"""
Model interaction module for the Human/Machine Sentence Classifier using OpenRouter.

This module provides classification functionality for determining whether text is human-written or machine-generated
using OpenRouter API with robust error handling, caching, and retry mechanisms.
"""

import os
import logging
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Dict, Any, Union

# Import configuration
try:
    from .config import get_config, AppConfig
except ImportError:
    # Fallback if config module is not available
    get_config = None

# Import caching
try:
    from .cache import get_cache, ResponseCache
except ImportError:
    # Fallback if cache module is not available
    get_cache = None

# Optional dependency for OpenRouter HTTP client
try:
    import requests
except Exception:
    requests = None

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- Configuration ---
# Allow default model name to be overridden by user home dotfile:
#   ~/.model-openrouter    -> overrides DEFAULT_OPENROUTER_MODEL
OPENROUTER_API_KEY_FILE_PATH = Path.home() / ".api-openrouter"
OPENROUTER_MODEL_FILE_PATH = Path.home() / ".model-openrouter"
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

# Hardcoded fallback if no override file is present
_DEFAULT_OPENROUTER_MODEL_FALLBACK = "openrouter/free"

def _read_text_file(path: Path) -> Optional[str]:
    """Read and strip text from a file path if it exists; return None on failure or empty.

    Args:
        path: Path to the file to read

    Returns:
        Stripped text content or None if file doesn't exist, is empty, or can't be read
    """
    try:
        if not path.exists():
            logging.debug(f"File does not exist: {path}")
            return None

        if not path.is_file():
            logging.debug(f"Path is not a file: {path}")
            return None

        content = path.read_text(encoding="utf-8").strip()
        return content or None

    except (IOError, OSError, UnicodeDecodeError) as e:
        logging.error(f"Failed to read text from {path}: {e}")
        return None
    except Exception as e:
        logging.error(f"Unexpected error reading {path}: {e}")
        return None

def _resolve_openrouter_default_model() -> str:
    """Resolve default OpenRouter model name from configuration system."""
    if get_config:
        config = get_config()
        return config.effective_openrouter_model

    # Fallback to legacy method
    override = _read_text_file(OPENROUTER_MODEL_FILE_PATH)
    return override if override else _DEFAULT_OPENROUTER_MODEL_FALLBACK

# Export resolved default so callers (e.g., CLI) can import it
DEFAULT_OPENROUTER_MODEL = _resolve_openrouter_default_model()

@dataclass
class ClassificationResult:
    """Result of a text classification attempt."""
    label: Optional[str] = None  # '0', '1', or None for failure
    confidence: Optional[float] = None  # Confidence score if available
    error: Optional[str] = None  # Error message if classification failed
    provider: Optional[str] = None  # 'openrouter'
    model: Optional[str] = None  # Model name used
    response_time: Optional[float] = None  # Time taken for classification

    @property
    def is_success(self) -> bool:
        """Check if classification was successful."""
        return self.label is not None and self.error is None

    @property
    def is_human(self) -> Optional[bool]:
        """Check if text was classified as human-written."""
        if not self.is_success:
            return None
        return self.label == '1'

    @property
    def is_machine(self) -> Optional[bool]:
        """Check if text was classified as machine-generated."""
        if not self.is_success:
            return None
        return self.label == '0'

def _shared_prompt(text: str) -> str:
    """Generate the shared classification prompt.

    Args:
        text: The text to classify

    Returns:
        Formatted prompt string for the AI model

    Raises:
        ValueError: If text is empty or None
    """
    if not text or not text.strip():
        raise ValueError("Text cannot be empty")

    # Sanitize text to prevent prompt injection
    sanitized_text = text.strip().replace("\\", "\\\\").replace("\"", "\\\"")

    return (
        "Classify the following sentence based on whether it sounds like it was "
        "written by a human or generated by a machine like an AI paraphrase tool.\n\n"
        "Categories:\n"
        "- '1': Human-written\n"
        "- '0': Machine-generated\n\n"
        "Respond with ONLY the digit '0' or '1'. Do not include any other text, "
        "explanation, or punctuation.\n\n"
        f"Sentence: \"{sanitized_text}\"\n\n"
        "Classification:"
    )

# ---------------- OpenRouter support ----------------

def _read_openrouter_key_file() -> Optional[str]:
    """Read OpenRouter API key from ~/.api-openrouter if present."""
    try:
        if OPENROUTER_API_KEY_FILE_PATH.is_file():
            logging.info(f"Reading OpenRouter API key from {OPENROUTER_API_KEY_FILE_PATH}")
            return OPENROUTER_API_KEY_FILE_PATH.read_text(encoding="utf-8").strip()
        return None
    except Exception as e:
        logging.error(f"Failed to read OpenRouter API key from {OPENROUTER_API_KEY_FILE_PATH}: {e}")
        return None

def _resolve_openrouter_api_key() -> Optional[str]:
    """Resolve OpenRouter API key using configuration system."""
    if get_config:
        config = get_config()
        return config.effective_openrouter_api_key

    # Fallback to legacy method
    env_key = os.getenv("OPENROUTER_API_KEY")
    if env_key and env_key.strip():
        return env_key.strip()
    return _read_openrouter_key_file()

def classify_with_openrouter(
    text: str,
    model_name: str = DEFAULT_OPENROUTER_MODEL,
    max_retries: int = 3,
    use_cache: bool = True
) -> ClassificationResult:
    """
    Classify using OpenRouter chat completions API. Returns ClassificationResult.

    Args:
        text: The text to classify
        model_name: Name of the OpenRouter model to use
        max_retries: Maximum number of retry attempts on failure
        use_cache: Whether to use caching for responses

    Returns:
        ClassificationResult with the classification outcome
    """
    result = ClassificationResult(provider="openrouter", model=model_name)

    # Input validation
    if not text or not text.strip():
        result.error = "Text cannot be empty"
        return result

    # Check cache first
    if use_cache and get_cache:
        cache = get_cache()
        cached_result = cache.get(text, "openrouter", model_name)
        if cached_result is not None:
            logging.debug("Using cached OpenRouter result")
            result.label = cached_result
            result.response_time = 0.0  # Cached result has no API latency
            return result

    start_time = time.time()

    if requests is None:
        result.error = "requests library not available. Install it to use OpenRouter support."
        return result

    api_key = _resolve_openrouter_api_key()
    if not api_key:
        result.error = "No OpenRouter API key found in OPENROUTER_API_KEY or ~/.api-openrouter"
        return result

    for attempt in range(max_retries):
        try:
            prompt = _shared_prompt(text)

            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            }
            payload = {
                "model": model_name,
                "messages": [
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.0,
                "max_tokens": 10  # Limit response length
            }

            resp = requests.post(
                OPENROUTER_API_URL,
                headers=headers,
                json=payload,
                timeout=60
            )

            if resp.status_code != 200:
                error_msg = f"OpenRouter API error {resp.status_code}: {resp.text[:200]}"
                if attempt < max_retries - 1:
                    logging.warning(f"{error_msg}, retrying (attempt {attempt + 1}/{max_retries})")
                    time.sleep(2 ** attempt)
                    continue
                else:
                    result.error = error_msg
                    return result

            data = resp.json()

            # Try to extract assistant message content
            generated_text = None
            choices = data.get("choices", [])
            if choices:
                msg = choices[0].get("message", {})
                generated_text = (msg.get("content") or "").strip()

            if not generated_text:
                error_msg = "OpenRouter response contained no text content"
                if attempt < max_retries - 1:
                    logging.warning(f"{error_msg}, retrying (attempt {attempt + 1}/{max_retries})")
                    time.sleep(2 ** attempt)
                    continue
                else:
                    result.error = error_msg
                    return result

            # Parse and validate response
            if generated_text in ("0", "1"):
                result.label = generated_text
                result.response_time = time.time() - start_time

                # Cache successful result
                if use_cache and get_cache:
                    cache = get_cache()
                    cache.put(text, "openrouter", model_name, result.label,
                            metadata={"response_time": result.response_time})

                return result

            # Heuristic fallback for ambiguous responses
            if "0" in generated_text and "1" not in generated_text:
                result.label = "0"
                result.response_time = time.time() - start_time

                # Cache successful result
                if use_cache and get_cache:
                    cache = get_cache()
                    cache.put(text, "openrouter", model_name, result.label,
                            metadata={"response_time": result.response_time})

                return result
            elif "1" in generated_text and "0" not in generated_text:
                result.label = "1"
                result.response_time = time.time() - start_time

                # Cache successful result
                if use_cache and get_cache:
                    cache = get_cache()
                    cache.put(text, "openrouter", model_name, result.label,
                            metadata={"response_time": result.response_time})

                return result

            # If we can't parse the response
            error_msg = f"Unexpected OpenRouter output: '{generated_text[:100]}...'. Expected '0' or '1'."
            if attempt < max_retries - 1:
                logging.warning(f"{error_msg}, retrying (attempt {attempt + 1}/{max_retries})")
                time.sleep(2 ** attempt)
                continue
            else:
                result.error = error_msg
                return result

        except requests.exceptions.Timeout:
            error_msg = "OpenRouter API request timed out"
            if attempt < max_retries - 1:
                logging.warning(f"{error_msg}, retrying (attempt {attempt + 1}/{max_retries})")
                time.sleep(2 ** attempt)
                continue
            else:
                result.error = error_msg
                return result

        except requests.exceptions.RequestException as e:
            error_msg = f"OpenRouter API request failed: {e}"
            if attempt < max_retries - 1:
                logging.warning(f"{error_msg}, retrying (attempt {attempt + 1}/{max_retries})")
                time.sleep(2 ** attempt)
                continue
            else:
                result.error = error_msg
                return result

        except Exception as e:
            error_msg = f"Unexpected error during OpenRouter API call: {e}"
            if attempt < max_retries - 1:
                logging.warning(f"{error_msg}, retrying (attempt {attempt + 1}/{max_retries})")
                time.sleep(2 ** attempt)
                continue
            else:
                result.error = error_msg
                return result

    result.error = "Max retries exceeded"
    return result

def classify_text(
    text: str,
    model: str = DEFAULT_OPENROUTER_MODEL,
    max_retries: int = 3,
    use_cache: bool = True
) -> ClassificationResult:
    """
    Unified function to classify text using OpenRouter.

    Args:
        text: The text to classify
        model: Model name for OpenRouter
        max_retries: Maximum number of retry attempts
        use_cache: Whether to use caching for responses

    Returns:
        ClassificationResult with the classification outcome
    """
    return classify_with_openrouter(text, model, max_retries, use_cache)

if __name__ == "__main__":
    print("--- Testing OpenRouter ---")
    example = "This is a sentence written by a real person, expressing a genuine thought."

    result = classify_with_openrouter(example)
    if result.is_success:
        print(f"Result: {result.label} (took {result.response_time:.2f}s)")
    else:
        print(f"Failed: {result.error}")
